// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<frc::SpeedController> RobotMap::driveBaseSubRearRightVictorSP;
std::shared_ptr<frc::SpeedController> RobotMap::driveBaseSubFrontLeftVictorSP;
std::shared_ptr<frc::SpeedController> RobotMap::driveBaseSubRearLeftVictorSP;
std::shared_ptr<frc::SpeedController> RobotMap::driveBaseSubFrontRightVictorSP;
std::shared_ptr<frc::RobotDrive> RobotMap::driveBaseSubrobotDrive;
std::shared_ptr<frc::SpeedController> RobotMap::intakeSubsystemSpeedController1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driveBaseSubRearRightVictorSP.reset(new frc::VictorSP(14));
    lw->AddActuator("DriveBaseSub", "RearRightVictorSP", std::static_pointer_cast<frc::VictorSP>(driveBaseSubRearRightVictorSP));
    
    driveBaseSubFrontLeftVictorSP.reset(new frc::VictorSP(0));
    lw->AddActuator("DriveBaseSub", "FrontLeftVictorSP", std::static_pointer_cast<frc::VictorSP>(driveBaseSubFrontLeftVictorSP));
    
    driveBaseSubRearLeftVictorSP.reset(new frc::VictorSP(1));
    lw->AddActuator("DriveBaseSub", "RearLeftVictorSP", std::static_pointer_cast<frc::VictorSP>(driveBaseSubRearLeftVictorSP));
    
    driveBaseSubFrontRightVictorSP.reset(new frc::VictorSP(15));
    lw->AddActuator("DriveBaseSub", "FrontRightVictorSP", std::static_pointer_cast<frc::VictorSP>(driveBaseSubFrontRightVictorSP));
    
    driveBaseSubrobotDrive.reset(new frc::RobotDrive(driveBaseSubFrontLeftVictorSP, driveBaseSubRearLeftVictorSP,
              driveBaseSubFrontRightVictorSP, driveBaseSubRearRightVictorSP));
    
    driveBaseSubrobotDrive->SetSafetyEnabled(false);
        driveBaseSubrobotDrive->SetExpiration(0.1);
        driveBaseSubrobotDrive->SetSensitivity(0.5);
        driveBaseSubrobotDrive->SetMaxOutput(1.0);

    intakeSubsystemSpeedController1.reset(new frc::PWMTalonSRX(13));
    lw->AddActuator("IntakeSubsystem", "Speed Controller 1", std::static_pointer_cast<frc::PWMTalonSRX>(intakeSubsystemSpeedController1));
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
